-- 𝐌𝐞𝐫𝐜𝐡𝐚𝐧𝐭 𝐑𝐞𝐯𝐞𝐧𝐮𝐞 𝐀𝐧𝐚𝐥𝐲𝐬𝐢𝐬 💭 Problem: A table contains: MerchantID, TransactionAmount, TransactionDate, Country.

-- Task 2: Write a query to calculate the 𝐭𝐨𝐭𝐚𝐥 𝐫𝐞𝐯𝐞𝐧𝐮𝐞 generated by each merchant over the 𝐥𝐚𝐬𝐭 𝐪𝐮𝐚𝐫𝐭𝐞𝐫, grouped by 𝐜𝐨𝐮𝐧𝐭𝐫𝐲.

SELECT
    MerchantID,
    Country,
    SUM(TransactionAmount) AS TotalRevenue
FROM Transactions
WHERE TransactionDate >= DATE_TRUNC('quarter', CURRENT_DATE) - INTERVAL '3 months'
  AND TransactionDate < DATE_TRUNC('quarter', CURRENT_DATE)
GROUP BY MerchantID, Country
ORDER BY Country, TotalRevenue DESC;

